---
name: GitHub Actions Validation
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/**.yml'
      - '.github/workflows/**.yaml'

jobs:
  github-actions-check:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout this repository
        uses: actions/checkout@v6.0.1

      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      - name: Check Workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color -shellcheck=
        shell: bash
